version: '3.2'
services:
  apache:
    restart: always
    image: httpd:2.4
    volumes:
      - ./apache/nuxtDeploy/:/usr/local/apache2/htdocs/
    ports:
      - 8091:80
  webhook:
    restart: always
    build:
      context: ./webhook
    volumes:
      - ./apache/nuxtDeploy/:/opt/application/nuxtDeploy
      - ./nuxt/:/opt/application/nuxtSource
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: krouin
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./strapi/app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - ./strapi/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: krouin
      MYSQL_USER: chloe
      MYSQL_PASSWORD: pass;1234
